### ISSUE TITLE
Topicos

### ISSUE THREAD

**Issue by Akiira23** [callmarx/MAC0218-project#2]
Topicos nao aparecem mais para serem escolhidos em "Novo Post"
Link para Topicos aparece "Desculpe! Você não tem acesso à essa página." mesmo conectado em uma conta

**Comment by callmarx** [comment]
Vc provavelmente esqueceu de dar `db:seed`. É necessário rodar antes  o comando completo de db: `rails db:create db:migrate db:seed faker:seed` como consta no README.
